import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import next from '@next/eslint-plugin-next';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';

/**
 * Flat config. The Next plugin is wired directly rather than through
 * `eslint-config-next`, whose legacy entry point pulls in an ESLint patch that
 * does not survive ESLint 9's flat config and breaks `next build`'s lint step.
 */
export default tseslint.config(
  // next-env.d.ts is generated by Next and is not ours to lint.
  { ignores: ['.next/**', 'out/**', 'node_modules/**', 'coverage/**', 'next-env.d.ts'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  next.flatConfig.coreWebVitals,
  {
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },
  prettier,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // Compute modules must stay pure and framework-free so they can later run
      // in a Web Worker, in WASM, or behind a public API.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['react', 'react-dom', 'next/*'],
              message: 'Compute modules must not import UI or framework code.',
            },
          ],
        },
      ],
    },
  },
  {
    // Build scripts run in Node, not the browser.
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        fetch: 'readonly',
        Buffer: 'readonly',
      },
    },
  },
  {
    // The restriction above applies only to the pure compute layer. Everything
    // listed here is presentation or client state and may use React.
    files: [
      'src/app/**',
      'src/components/**',
      'src/hooks/**',
      'src/tools/**/ui.tsx',
      'src/lib/tools/components.ts',
    ],
    rules: { 'no-restricted-imports': 'off' },
  },
);
